# Simple workflow for deploying static content to GitHub Pages
name: Trigger GeodeSDK Site Build

on:
    push:
        branches: ["main"]
    
    workflow_dispatch:

jobs:
    trigger:
        name: Trigger site build
        runs-on: ubuntu-latest
        steps:
        - uses: actions/github-script@v6
          with:
            github-token: ${{ secrets.GEODE_BOT_PUSH_BIN_TOKEN }}
            script: |
                await github.rest.actions.createWorkflowDispatch({
                    owner: 'geode-sdk',
                    repo: 'website',
                    workflow_id: 'build.yml',
                    ref: 'main'
                })
